### PR TITLE
closes halt-hammerzeit/webpack-isomorphic-tools#49

### PR DESCRIPTION
**Pull request by catamphetamine**
You may also check out a complete usage example
https://github.com/halt-hammerzeit/webapp

### CODE REVIEW

**Comment by veeracs** [comment]
@halt-hammerzeit 
Awesome! will check out. Thanks for all the help and webpack goodness :+1:

**Comment by veeracs** [comment]
@halt-hammerzeit 

webpack-isomorphic-tools/plugin is complaining about no source, although the SCSS has source. I'll see if I can figure this out. That's probably because the SCSS linting may be failing.

```
⚡ npm run dev

> isomorphic-tools-seed@0.0.0 dev /Users/csekharveera/Sites/isomorphic-tools-seed
> webpack --config ./webpack/dev.config.js && better-npm-run start-dev

[webpack-isomorphic-tools/plugin] [error] Module "./lib/app/layouts/Base.scss" has no source. Maybe Webpack compilation of this module failed. Skipping this asset.
[webpack-isomorphic-tools/plugin] [error] Module "./lib/client/assets/styles/app.scss" has no source. Maybe Webpack compilation of this module failed. Skipping this asset.
Hash: 939d31159439dbda31ef
Version: webpack 1.12.11
Time: 9503ms
     Asset     Size  Chunks             Chunk Names
    app.js  1.16 MB       0  [emitted]  main
app.js.map   1.4 MB       0  [emitted]  main
    + 529 hidden modules

ERROR in ./lib/client/assets/styles/app.scss
Module build failed: YAMLException: duplicated mapping key at line 21, column 19:
      nesting-depth: 0
                      ^
    at generateError (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1065:9)
    at composeNode (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readBlockMapping (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at module.exports (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/lib/config.js:89:21)
    at Function.sassLint.getConfig (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/index.js:25:10)
    at Function.sassLint.lintText (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/index.js:98:28)
    at lint (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/index.js:21:25)
    at Object.module.exports (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/index.js:99:7)
 @ ./lib/client/index.js 25:0-35

ERROR in ./lib/app/layouts/Base.scss
Module build failed: YAMLException: duplicated mapping key at line 21, column 19:
      nesting-depth: 0
                      ^
    at generateError (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1065:9)
    at composeNode (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readBlockMapping (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at module.exports (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/lib/config.js:89:21)
    at Function.sassLint.getConfig (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/index.js:25:10)
    at Function.sassLint.lintText (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/node_modules/sass-lint/index.js:98:28)
    at lint (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/index.js:21:25)
    at Object.module.exports (/Users/csekharveera/Sites/isomorphic-tools-seed/node_modules/sasslint-loader/index.js:99:7)
 @ ./lib/app/layouts/Base.js 25:0-22
running better-npm-run in /Users/csekharveera/Sites/isomorphic-tools-seed
Executing script: start-dev

to be executed: node ./bin/app-server
Webpack is all set now....
[webpack-isomorphic-tools] [error] asset not found: ./lib/app/layouts/Base.scss
```

**Comment by catamphetamine** [comment]
Yes, you should fix these errors

```
ERROR in ./lib/client/assets/styles/app.scss
Module build failed: YAMLException: duplicated mapping key at line 21, column 19:
      nesting-depth: 0
```

```
ERROR in ./lib/app/layouts/Base.scss
Module build failed: YAMLException: duplicated mapping key at line 21, column 19:
      nesting-depth: 0
```

I don't have them in `npm run dev` and fresh `npm install`

**Comment by veeracs** [comment]
@halt-hammerzeit 

I fixed those errors in the latest commit, please checkout. The CSS/SCSS is not getting compiled. The page (@localhost:8080) loads without any styling even though isomorphic-tools-plugin runs without errors. I wish it showed some errors with unable to fetch/generate scss/css errors.

The webpack-assets.json has empty styles object, although ./lib/app/layouts/Base.scss and ./lib/client/assets/styles/app.scss exist and were referred by ./lib/app/layouts/Base.js and ./lib/client/index.js respectively.

```
{"javascript":{"main":"/build/app.js"},"styles":{},
```

Appreciate your time and help, I'm close to getting this working.

**Comment by catamphetamine** [comment]
Fixed
https://github.com/veeracs/isomorphic-tools-seed/pull/2

**Comment by veeracs** [comment]
Awesome @halt-hammerzeit. Thank you sir. Every one develops tools, but one with zero issues, it's something :)

**Comment by catamphetamine** [comment]
I believe in making difference )

**Pull request merged**
